### ISSUE TITLE
shallow clones can not be pushed to a different remote repo

### ISSUE THREAD

**Issue by agrawalabhishek** [kartikkumar/cppbase#1]
I cloned this project with depth=1, changed the "origin" to an existing empty repo on my page and when I tried pushing the local repo to the remote, it gave me an error that shallow clones can not be pushed to the remote. Is there another way to push shallow clones to  a different remote repo?

**Comment by agrawalabhishek** [comment]
Found the solution. After the shallow clone, do `git commit --amend`. It'll rewrite the last commit message and remove the trace of a shallow copy. I tried this method and it worked. Alternatively, one can change the depth of the shallow clone to 2 instead of 1, I haven't tried this method but logically it could work.

**Comment by kartikkumar** [comment]
Hey Abhi, I didn't see this issue earlier. Glad that you sorted it out. I'll add the `amend` command in the readme.
