### ISSUE TITLE
Replace "add_definitions" by "add_compile_definitions"

### ISSUE THREAD

**Issue by kartikkumar** [kartikkumar/cppbase#5]
Currently, the version of CMake built from source for the Travis CI build doesn't support `add_compile_definitions`. This means that for PR #3, the deprecated `add_definitions` has to be used instead. 

To switch to `add_compile_definitions`, the CMake version has to be bumped up, but initial testing shows that this causes issues for the custom Doxygen scripts for the Travis CI build, because of updates in `FindDoxygen.cmake`. 

So this issue requires both the CMake and Doxygen scripts for Travis to be updated.

**Comment by remyabel** [comment]
Why not use the import targets instead? Example:

    find_package(Catch2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Catch2::Catch2)

This should work with CMake 3.9.2 (the one Travis uses).

**Comment by remyabel** [comment]
Disregard my last comment. What about using [`target_compile_definitions`](https://cmake.org/cmake/help/v3.7/command/target_compile_definitions.html)?

**Comment by kartikkumar** [comment]
So I didn't realize that Travis ships with a newer version of CMake now. Used to be 2.8 I think, which is why I set up a custom script to build from source.

I'll try to investigate use of `add_compile_definitions` or `target_compile_definitions`, using the version of CMake that's native to Travis VMs now. Just have to make sure it doesn't break the Doxygen setup.

Thanks for the suggestion!

**Comment by kartikkumar** [comment]
Obsolete with the migration to the new, modern CMake setup, as of https://github.com/kartikkumar/cppbase/commit/2d941d33d26eb66796ff6395aba8e13242bdbe18
