### ISSUE TITLE
Use include(CTest)

### ISSUE THREAD

**Issue by ghost** [kartikkumar/cppbase#6]
Currently you have `enable_testing()` and a custom `BUILD_TESTS` flag. This functionality is already provided in [CMake](https://gitlab.kitware.com/cmake/community/wikis/doc/ctest/Testing-With-CTest). Diff:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 22b3617..2ac71a0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -130,8 +130,10 @@ if(BUILD_DOXYGEN_DOCS)
                     SOURCES ${PROJECT_BINARY_DIR}/Doxyfile)
 endif(BUILD_DOXYGEN_DOCS)
 
-if(BUILD_TESTS)
-  enable_testing()
+# Calls enable_testing() and provides BUILD_TESTING flag
+include(CTest)
+
+if(BUILD_TESTING)
   set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${TEST_PATH})
 
   add_executable(${TEST_NAME} ${TEST_SRC})
```

You will need to replace `BUILD_TESTS` with `BUILD_TESTING` everywhere and wrap appropriate blocks.

**Comment by kartikkumar** [comment]
Thanks for the suggestion! Good way to streamline the CMakeLists setup indeed. I'll try to get on this asap.
